sudo: required
services:
  - docker

before_install:
  - docker build -t ibrahem2910/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true ibrahem2910/react-test npm test -- --coverage
after_success:
  - docker build -t ibrahem2910/multi-client ./client 
  - docker build -t ibrahem2910/multi-nginx ./nginx
  - docker build -t ibrahem2910/multi-server ./server
  - docker build -t ibrahem2910/multi-worker ./worker 
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | doccker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push ibrahem2910/multi-client
  - docker push ibrahem2910/multi-nginx
  - docker push ibrahem2910/multi-server
  - docker push ibrahem2910/multi-worker
